VCubWatcher/Models/ErrorViewModel.cs
using System;

namespace VCubWatcher.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VCubWatcher/Models/Stations.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace VCubWatcher.Models
{
    public class Station
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("bike_count")]
        public int BikeCount { get; set; }

        [JsonProperty("electric_bike_count")]
        public int ElectricBikeCount { get; set; }

        [JsonProperty("bike_count_total")]
        public int BikeCountTotal { get; set; }

        [JsonProperty("slot_count")]
        public int SlotCount { get; set; }

        [JsonProperty("is_online")]
        public bool IsOnline { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }
    }
}

VCubWatcher/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VCubWatcher.Models;

namespace VCubWatcher.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VCubWatcher/Controllers/StationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using VCubWatcher.Models;

namespace VCubWatcher.Controllers
{
    public class StationController : Controller
    {
        public static List<Station> StationsList = new List<Station>();

        // GET: StationController
        public StationController()
        {
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage response = client.GetAsync("https://api.alexandredubois.com/vcub-backend/vcub.php").Result)
                {
                    using (HttpContent content = response.Content)
                    {
                        var json = content.ReadAsStringAsync().Result;
                        StationsList = JsonConvert.DeserializeObject<List<Station>>(json);
                    }
                }
            }
        }
        public ActionResult Index()
        {
            return View(StationsList);
        }

        public IActionResult Map()
        {
            return View(StationsList);
        }

        public IActionResult Favorites()
        {
            return View(StationsList);
        }

        // GET: StationController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StationController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StationController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StationController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

VCubWatcher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VCubWatcher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VCubWatcher</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Index">Liste des stations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Map">Carte</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Favorites">Mes favoris</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VCubWatcher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VCubWatcher/Views/Station/Favorites.cshtml
@{
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
        <style type="text/css">
            #map {
                height: 400px;
            }

            img.huechange {
                filter: hue-rotate(120deg);
            }
        </style>
        <title>Carte</title>
    </head>
    <body>
        <div id="map">
        </div>

        <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
        <script type="text/javascript">
            var lat = 44.8333;
            var lon = -0.5667;
            var geo = navigator.geolocation;
            var test = navigator.geolocation.getCurrentPosition(success, error)
            var carte = null;

            function success(pos) {
                var crd = pos.coords;
                lat = crd.latitude;
                lon = crd.longitude;
            }

            function error(err) {
                console.warn(`ERROR(${err.code}): ${err.message}`);
            }

            function updateCookie(station) {
                document.cookie = document.cookie.replace(station, "");
                document.location.reload();
            }

            function initMap() {
                carte = L.map('map').setView([lat, lon], 15);
                L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
                    attribution: 'données © <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu <a href="//openstreetmap.fr">OSM France</a>',
                    minZoom: 1,
                    maxZoom: 20
                }).addTo(carte);
                var marker = L.marker([lat, lon]).addTo(carte);
                marker._icon.classList.add("huechange");
                @foreach (var station in Model)
                {
                    var popup = String.Format("Nombre de vélos : {0}     Nombre de places : {1}", @station.SlotCount, station.BikeCountTotal);
                    var temp = String.Format("<br><button onclick=updateCookie('{0}') class='btn btn-warning'>Retirer des favoris</button>", @station.Name.Replace(" ", "").Replace("'", ""));
                    var name = @station.Name.Replace(" ", "").Replace("'", "");
                    <text>{
                    if (document.cookie.split(",").includes("@name")) {
                        var marker = L.marker([@station.Latitude, @station.Longitude],
                        {
                            title: '@station.Name',
                        }
                        ).addTo(carte);
                        marker.bindPopup("@popup @Html.Raw(temp)");
                    }
                    }</text>
                    }
                }

            window.onload = function () {
                initMap();
            };
        </script>
    </body>
</html>
}

VCubWatcher/Views/Station/Index.cshtml
@model List<Station>
@using System.Web;

@{
    ViewData["Title"] = "Stations";
}

@{
    <script src="https://use.fontawesome.com/98e82c05d5.js"></script>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nom de la station</th>
                <th scope="col">Nombre de vélos électriques</th>
                <th scope="col">Nombre de vélos total</th>
                <th scope="col">Emplacement libres</th>
                <th scope="col">En service</th>
                <th scope="col">Favoris</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var station in Model)
            {
                var name = @station.Name.Replace(" ", "").Replace("'", "");
                <tr>
                    <td>@station.Name</td>
                    <td>@station.ElectricBikeCount</td>
                    <td>@station.BikeCountTotal</td>
                    <td>@station.SlotCount</td>
                    @if (station.IsOnline)
                    {
                        <td class="table-success"></td>
                    }
                    else
                    {
                        <td class="table-danger"></td>
                    }
                </tr>
            }

        </tbody>
    </table>
}

VCubWatcher/Views/Station/Map.cshtml
@model List<Station>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
        <style type="text/css">
            #map {
                height: 400px;
            }

            img.huechange {
                filter: hue-rotate(120deg);
            }
        </style>
        <title>Carte</title>
    </head>
    <body>
        <div id="map">
        </div>

        <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
        <script type="text/javascript">
            var lat = 44.8333;
            var lon = -0.5667;
            var geo = navigator.geolocation;
            var test = navigator.geolocation.getCurrentPosition(success, error)
            var carte = null;

            function success(pos) {
                var crd = pos.coords;
                lat = crd.latitude;
                lon = crd.longitude;
            }

            function error(err) {
                console.warn(`ERROR(${err.code}): ${err.message}`);
            }

            function updateCookie(station) {
                if (!(document.cookie.split(",").includes(station))) {
                    var basecookie = document.cookie;
                    var append = station + ",";
                    document.cookie = basecookie + append;
                }
            }

            function initMap() {
                carte = L.map('map').setView([lat, lon], 15);
                L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
                    attribution: 'données © <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu <a href="//openstreetmap.fr">OSM France</a>',
                    minZoom: 1,
                    maxZoom: 20
                }).addTo(carte);
                var marker = L.marker([lat, lon]).addTo(carte);
                marker._icon.classList.add("huechange");
                @foreach (var station in Model)
                {
                    var popup = String.Format("Nombre de vélos : {0}      Nombre de places : {1}", @station.SlotCount, station.BikeCountTotal);
                    var temp = String.Format("<br><button onclick=updateCookie('{0}') class='btn btn-warning'>Ajouter aux favoris</button>", @station.Name.Replace(" ","").Replace("'", ""));
                    <text>{
                    var marker = L.marker([@station.Latitude, @station.Longitude],
                        {
                            title: '@station.Name',
                        }
                    ).addTo(carte);
                    marker.bindPopup("@popup @Html.Raw(temp)");
                    }</text>
                }

            }
            window.onload = function () {
                initMap();
            };
        </script>
    </body>
</html>
}